name: Build, Push and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Allow SSH access from GitHub Actions runner
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/temp_key
          chmod 600 ~/.ssh/temp_key
          mv ~/.ssh/temp_key ~/.ssh/id_rsa

          # Add the host to the known_hosts file
          ssh-keyscan your-instance-ip >> ~/.ssh/known_hosts

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: bash scripts/build_and_push.sh

      - name: Deploy to AWS
        run: bash scripts/deploy.sh

      - name: Cleanup SSH key
        run: rm ~/.ssh/id_rsa
