name: Build and Push, Update security group and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: bash scripts/build_and_push.sh

      - name: Get Public IP
        id: public_ip
        run: echo "PUBLIC_IP=$(curl ifconfig.me)" > env.list

      - name: Update Security Group
        run: |
          aws ec2 authorize-security-group-ingress --group-id sg-05ba363da649d4ef2 --protocol tcp --port 22 --source "${{ env.PUBLIC_IP }}"

      - name: Deploy to AWS
        run: bash scripts/deploy.sh
